feature/chats
Vokoloven/sales-assistant pull request #34
Opened 2024-03-29 12:52 UTC by Vokoloven

In this ticked I created CRUD for messages.

2024-04-02 07:54 UTC, AndriiKasian commented
- [ ] when we click the "New Chat" button and the modal appears, the text field shouldn't contain the previous value inside

2024-04-02 08:02 UTC, AndriiKasian commented
- [ ]  when I was trying to create a new Chat, but my token was expired. Here is a happy pass case: before sending some request to the server you have to check the token and update it if it's needed, and after that continue to send request with the new token.

<img width="1413" alt="Снимок экрана 2024-04-02 в 10 55 20" src="https://github.com/Vokoloven/sales-assistant/assets/38005788/abb35621-ee0a-4170-95b3-ba13fc9d9b20">

2024-04-02 09:21 UTC, AndriiKasian requested changes

2024-04-02 09:21 UTC, AndriiKasian commented on src/App.tsx
> +const Chat = lazy(() => import("./pages/Chat/Chat"));
- [ ] check the conversation tab, I left comments there

2024-04-05 12:44 UTC, AndriiKasian requested changes

2024-04-05 12:44 UTC, AndriiKasian commented on src/hooks/useContainerDimension.ts
> +  const height = () => {
- [ ] what is the main idea of this hook?

2024-04-05 12:44 UTC, AndriiKasian commented on src/hooks/useCreateChat.tsx
> +export const useCreateChat = () => {
- [ ] rename useCreateChat to useCreateChatModal

2024-04-05 13:59 UTC, Vokoloven commented on src/components/Shared/Header.tsx
> +              // onClick={() => openModal()}
Yes we this button will shown when device resolution as tablet and less.
<img width="995" alt="image" src="https://github.com/Vokoloven/sales-assistant/assets/48805990/780c3cdf-ee18-417b-a512-a685347042a9">

2024-04-08 08:40 UTC, AndriiKasian approved these changes

2024-04-11 12:17 UTC, AndriiKasian submitted a review, later dismissed

2024-04-11 13:57 UTC, merged