Feature/tooltip
Vokoloven/sales-assistant pull request #37
Opened 2024-04-05 13:12 UTC by Vokoloven

> [!IMPORTANT]
> PLEASE REVIEW ONLY AFTER FINISH WITH [THIS PR](https://github.com/Vokoloven/sales-assistant/pull/36)

This is the tooltip for aside menu.

<img width="748" alt="image" src="https://github.com/Vokoloven/sales-assistant/assets/48805990/727950a5-6f89-44b3-b9cc-301e9dc9da87">

 @AndriiKasian  How do you think good idea to make debounce for it?

2024-04-05 13:32 UTC, AndriiKasian requested changes

2024-04-05 13:32 UTC, AndriiKasian commented on src/components/Shared/Chat/RowButton.tsx
> +  const [tooltip, setTooltip] = useState(false);
- [ ] you can create tooltip as a Modal in the separate hook

2024-04-05 13:33 UTC, AndriiKasian commented
- [ ] set debounce for the tooltip

2024-04-05 19:23 UTC, Vokoloven commented on src/components/Shared/Chat/RowButton.tsx
> +  const [tooltip, setTooltip] = useState(false);
I made custom hook, all logics incapsulated inside.

2024-04-08 08:48 UTC, AndriiKasian approved these changes

2024-04-08 10:34 UTC, merged